#!/usr/bin/env bash
#
# Stage 1 entrypoint — plan.md -> GitHub issues.
#
# Env:
#   REPO                owner/name                    (required)
#   GH_TOKEN            GitHub token, repo+issues     (required)
#   ANTHROPIC_API_KEY   Claude API key               (required)
#   SLICER_DRY_RUN      1 = print, do not create issues   (default 0)
#   MAX_ISSUES          hard cap on issues per run        (default 25)
#
set -euo pipefail
STAGE=slicer
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "$HERE/../lib/common.sh"

require_env REPO GH_TOKEN ANTHROPIC_API_KEY
MAX_ISSUES="${MAX_ISSUES:-25}"
DRY_RUN="${SLICER_DRY_RUN:-0}"

workdir="$(clone_repo)"
cd "$workdir"

if [[ ! -f plan.md ]]; then
  log "$STAGE" "no plan.md in $REPO; nothing to do"
  exit 0
fi

mkdir -p .agent
python3 "$HERE/../lib/parse_plan.py" plan.md > .agent/items.tsv
log "$STAGE" "found $(wc -l < .agent/items.tsv) unchecked action item(s)"

created=0
while IFS=$'\t' read -r fp type text; do
  [[ -z "$fp" ]] && continue

  if (( created >= MAX_ISSUES )); then
    log "$STAGE" "hit MAX_ISSUES=$MAX_ISSUES; stopping"
    break
  fi

  # Dedupe: the fingerprint is written into every issue body as visible text.
  hits="$(gh issue list --repo "$REPO" --state all --limit 1 \
            --search "\"agent-fingerprint:$fp\"" --json number --jq 'length')"
  if [[ "$hits" != "0" ]]; then
    log "$STAGE" "skip (already sliced): $text"
    continue
  fi

  rm -f .agent/issue.json
  run_claude "You are expanding ONE action item from plan.md into a GitHub issue
for a Python project.

Action item: \"$text\"
Suggested type (you may override): \"${type:-unknown}\"

Read the repository so the issue points at real files. Then write STRICT JSON to
.agent/issue.json with exactly these keys:
  title  - concise, imperative
  body   - markdown with three sections: Context, Acceptance Criteria
           (3-6 '- [ ]' checkboxes, each independently testable), Likely files
  type   - one of: feature, bug, refactor, docs, chore

Do not propose scope beyond the action item. Write nothing except the file." \
    --max-turns 30

  if [[ ! -f .agent/issue.json ]]; then
    log "$STAGE" "agent produced no issue.json for: $text"
    jlog "$STAGE" "\"fingerprint\":\"$fp\",\"status\":\"no-output\",\"item\":$(jq -Rc . <<<"$text")"
    continue
  fi

  title="$(jq -r .title .agent/issue.json)"
  body="$(jq -r .body  .agent/issue.json)"
  itype="$(jq -r .type .agent/issue.json)"
  case "$itype" in feature|bug|refactor|docs|chore) ;; *) itype="chore" ;; esac

  full_body="$body

---
\`agent-fingerprint:$fp\`
_Generated by the agentic-dev slicer from \`plan.md\`._"

  labels="agent-generated,needs-tests,$itype"

  if [[ "$DRY_RUN" == "1" ]]; then
    log "$STAGE" "DRY_RUN would create [$labels] $title"
  else
    url="$(gh issue create --repo "$REPO" --title "$title" \
             --body "$full_body" --label "$labels")"
    log "$STAGE" "created $url"
    jlog "$STAGE" "\"fingerprint\":\"$fp\",\"issue\":\"$url\",\"type\":\"$itype\",\"status\":\"created\""
  fi
  created=$((created + 1))
done < .agent/items.tsv

log "$STAGE" "done; $created new item(s) processed"
